/* Automatically generated by './build/bin/build-entry.js' */

import Pagination from '../packages/pagination/index.js';
import DatePicker from '../packages/date-picker/index.js';
import Alert from '../packages/alert/index.js';
import Notification from '../packages/notification/index.js';
import Loading from '../packages/loading/index.js';
import Upload from '../packages/upload/index.js';
import Progress from '../packages/progress/index.js';
import Select from '../packages/select/index.js';
import Option from '../packages/option/index.js';
import InfiniteScroll from '../packages/infiniteScroll/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Pagination,
  DatePicker,
  Alert,
  Upload,
  Progress,
  Select,
  Option,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$notify = Notification;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.9.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Pagination,
  DatePicker,
  Alert,
  Notification,
  Upload,
  Progress,
  Select,
  Option,
  InfiniteScroll
};
